#!/usr/bin/python3
import sys

def main():
    next_biggest_number(sys.argv[1])


def next_biggest_number(n):
        arr = [c for c in str(n)]
        for i in range(len(arr) - 2, -1, -1):
            r = len(arr) - 1
            while i < r and arr[r] <= arr[i]:
                r -= 1
            if i != r:
                arr[i], arr[r] = arr[r], arr[i]
                arr[i + 1:] = sorted(arr[i + 1:])
                num = int("".join(arr))
                return num if num <= 2 ** 31 - 1 else -1
        return -1

if __name__ == "__main__":
    main()
